# Generated by Django 4.2.1 on 2023-05-23 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 17, 46, 25, 829365, tzinfo=datetime.timezone.utc)),
        ),
    ]
